apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::566972129213:role/eksctl-mycluster1-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-14T21:05:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "127654"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 24030590-44f8-4227-80ac-c6160e0f98a4
