---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mycluster1
  region: eu-west-1

managedNodeGroups:
- name: ng-experiment
  desiredCapacity: 2
  minSize: 1
  maxSize: 3
  privateNetworking: true 
  launchTemplate:
    id: "lt-0d12d37d8cf342b8e"
  iam:
    withAddonPolicies:
      externalDNS: true
      certManager: true
      ebs: true
      efs: true
      albIngress: true
      autoScaler: true
      cloudWatch: true

